export const demoActivity = [
  {
    id: 'demo-mint-1',
    demo: true,
    is_mint: true,
    wallet_label: 'Demo smart wallet',
    wallet_address: '0x82f4a2cbbd07c7e8c281d53a44706e7ac8f27191',
    contract_name: 'Sample Genesis',
    contract_address: '0x706daf3b6312852a2cba0f62ab7aea4f57ee941f',
    method_name: 'mint()',
    value_eth: '0.04',
    chain: 'eth',
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-contract-1',
    demo: true,
    is_mint: false,
    wallet_label: 'Demo deployer',
    wallet_address: '0x4cd00e4f7d1ad9a2118ac26d43fc2ef9200a8d51',
    contract_name: 'New mint contract',
    contract_address: '0x8b6df4b78f8d1fd2a80f0dd31ad44aa28c0f1091',
    method_name: 'contract deployed',
    value_eth: '0',
    chain: 'base',
    timestamp: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-risk-1',
    demo: true,
    is_mint: false,
    wallet_label: 'Demo risk signal',
    wallet_address: '0xf3a1d4d9cc7cbfa2bcd9c0372f70466d3414d7a3',
    contract_name: 'Unverified collection',
    contract_address: '0x91c5fb2fe2c9d437ab12a8de4f0ca77423dbe1a4',
    method_name: 'risk flagged',
    value_eth: '0',
    chain: 'eth',
    timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
  },
]

export const demoFeedEvents = [
  {
    id: 'demo-feed-1',
    type: 'whale_mint',
    title: 'Demo: smart wallet minted Sample Genesis',
    message: 'Copy Mint can turn this into a MintGuard project in Confirm Mode.',
    at: demoActivity[0].timestamp,
    demo: true,
  },
  {
    id: 'demo-feed-2',
    type: 'mint_countdown',
    title: 'Demo: mint countdown detected',
    message: 'Alpha Hub shows local time and UTC before Auto Beta can arm.',
    at: demoActivity[1].timestamp,
    demo: true,
  },
  {
    id: 'demo-feed-3',
    type: 'telegram_alert',
    title: 'Demo: Telegram alert delivered',
    message: 'Commands: /dashboard, /live, /upcoming, /help.',
    at: demoActivity[2].timestamp,
    demo: true,
  },
]
