alter table wl_projects
  add column if not exists automint_enabled boolean default false,
  add column if not exists max_mint_price numeric,
  add column if not exists max_gas_fee numeric,
  add column if not exists max_total_spend numeric,
  add column if not exists mint_time_source text,
  add column if not exists mint_time_confidence text,
  add column if not exists mint_time_confirmed boolean default false,
  add column if not exists mint_time_confirmed_at timestamptz,
  add column if not exists prepared_to text,
  add column if not exists prepared_data text,
  add column if not exists prepared_value text,
  add column if not exists prepared_chain_id integer,
  add column if not exists prepared_at timestamptz,
  add column if not exists gas_estimate text,
  add column if not exists simulation_status text,
  add column if not exists simulation_error text,
  add column if not exists execution_status text default 'queued',
  add column if not exists execution_reason text,
  add column if not exists prepare_started_at timestamptz,
  add column if not exists simulation_started_at timestamptz,
  add column if not exists simulated_at timestamptz,
  add column if not exists execution_started_at timestamptz,
  add column if not exists submitted_at timestamptz,
  add column if not exists confirmed_at timestamptz,
  add column if not exists time_to_prepare_ms integer,
  add column if not exists time_to_simulate_ms integer,
  add column if not exists time_to_submit_ms integer,
  add column if not exists rpc_latency_ms integer,
  add column if not exists confirmation_time_ms integer;
